spring:
  application:
    name: taskmanager
  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect # https://github.com/hibernate/hibernate-orm/blob/main/hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/SQLiteDialect.java
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:../database/taskmanager.sqlite3
    username: sqlite
    password: sqlite
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/auth/realms/taskmanager
rsa:
  private-key: classpath:certs/private.pem
  public-key: classpath:certs/public.pem